### ISSUE TITLE
Icon alignment issue

### ISSUE THREAD

**Issue by onemarshall** [CodyHouse/cd-input-icon-changelog#1]
Hi, it look's like there is an icon alignment issue, see image below!

![Screenshot 2020-09-30 at 07 38 38](https://user-images.githubusercontent.com/59648/94651214-038e5c00-02f0-11eb-8072-27399757e769.png)

**Comment by claudia-romano** [comment]
Hi there,
thanks for the heads-up! There was an issue with our demo. It has been fixed now. 

The component CSS code was not updated (the issue was with our demo style only). Cheers!
